---
- name: Server configuration
  hosts: all
  become: yes

  tasks:
    - name: setup server base
      include_role:
        name: bibi.server_setup

    - name: setup algo server
      include_role:
        name: bibi.algo_server
