    - name: Update apt packages
      apt:
        upgrade: dist
        update_cache: true
        state: latest

    - name: Check if reboot-required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: reboot
      reboot:
      when: reboot_required.stat.exists

    - name: Install Ubuntu packages
      apt:
        pkg:
          - python3-pip
          - atop

    - name: Install python packages
      ansible.builtin.pip:
        name:
          - stormssh
          - python-binance
          - pandas
          - mplfinance
          - sqlalchemy
          - ta
          - backtrader
          - pandas_ta
          - scipy
          - yfinance